# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=200)),
                ('ac3Time', models.FloatField(null=True)),
                ('geneTime', models.FloatField(null=True)),
            ],
        ),
    ]
